### ISSUE TITLE
How to run top search result from code?

### ISSUE THREAD

**Issue by danijar** [hpi-swa-teaching/Algernon-Launcher-old#12]
For writing tests, I need to run the best search result. This is what I've tried, but  `defaultAlgeraction` is not defined.

```
algerstance relevantAlgertemsFor: 'Senders of Morph#abandon' first defaultAlgeraction
```

**Comment by fawind** [comment]
Try this:

```
algerstance show.
algerstance textField contents: 'Senders of Morph#abandon'.
algerstance updateItemList.
algerstance selectNext.
algerstance doActionOnSelectedEvent:nil.
```

**Comment by janukobytsch** [comment]
It's really annoying how you cannot run the default action associated with an Algertem programmatically but have to loop over all items until the desired one is selected and then call doActionOnSelectedEvent:nil. There are method stubs for running an action, however, they are still buggy. I feel like it would be a good idea to fix this for future tests.

**Comment by danijar** [comment]
Yes, this is definitely a refactoring candidate for me. It feels like the existing architecture was written too tightly coupled to the UI and some buggy workarounds were added later to allow for testing. Thanks for your replies.
