### ISSUE TITLE
Rank recent choices higher

### ISSUE THREAD

**Issue by fawind** [hpi-swa-teaching/Algernon-Launcher-old#15]

**Comment by janukobytsch** [comment]
This feature already seems to be in place, isn't it?

**Comment by Dencrash** [comment]
At the moment we only priotize by the number of times an item has been chose. This feature is meant to really rank recent choices higher.

**Comment by janukobytsch** [comment]
I see. Please implement this in a way that we can easily change the parameters for the relevancy of an individual result (e.g. if we factor in fuzziness)

**Comment by koogle** [comment]
How does ist contribute to the overall rank now?
