### ISSUE TITLE
Implement fuzzy search

### ISSUE THREAD

**Issue by fawind** [hpi-swa-teaching/Algernon-Launcher-old#21]
Search algerterms using a fuzzy search algorithm

**Comment by fawind** [comment]
With: @koogle and @janukobytsch

**Comment by koogle** [comment]
Added stackoverflow impl

**Comment by danijar** [comment]
Thanks, Jake. Do you have a link to the Stackoverflow post?

**Comment by koogle** [comment]
http://stackoverflow.com/questions/16907825/how-to-implement-sublime-text-like-fuzzy-search

**Comment by koogle** [comment]
updated with 9428140b1ae0e7f8bc5cf0a8308b172543c5aa62 but fault tolerance needs a check it gets filtered somewhere else
tests are still failing
@janukobytsch can you have look into that

**Comment by janukobytsch** [comment]
Characters matched by the fuzzy search are actually highlighted now. This should facilitate the improvement of this feature I guess.

**Comment by danijar** [comment]
Looks pretty good
