### ISSUE TITLE
Error: UndefinedObject>>selectedAlgernonListItem

### ISSUE THREAD

**Issue by fawind** [hpi-swa-teaching/Algernon-Launcher-old#34]
How to reproduce:
1. Open Algernon
2. Search for a class
3. Jump into the class (`arrow right`)
4. Search for a method
5. Leave the class view (`arrow left`)

**Comment by fawind** [comment]
Not worth fixing since the whole parent-child hierarchy will be gone with the new UI next week

**Comment by janukobytsch** [comment]
@fawind The hierarchy is actually not going to change except for the action submenu being merged into the search results. The issue has however been fixed in the new development branch.
