### ISSUE TITLE
After opening a class, Algernon only shows methods

### ISSUE THREAD

**Issue by codeZeilen** [hpi-swa-teaching/Algernon-Launcher-old#59]
I started with a blank Algernon:

``` Smalltalk
ALGItemProvider initializeItems.
ALGCore initializeAlgernon.
```

I then opened Algernon and searched for "String". I opened the submenu and chose to open it in a new browser window. If I now open Algernon again and search for "String" again, the list only shows methods.

**Comment by janukobytsch** [comment]
Can't seem to reproduce this - can you provide me with further information regarding your image / vm?

**Comment by codeZeilen** [comment]
I'm using the current SWA Squeak Image. To set Algernon up, I've used the Baseline from the Readme.

**Comment by fawind** [comment]
It looks like that the itemProvider cache does not get cleared properly. When toggling the panel the method `self itemProvider resultsFor: ''` (ALGCore context) still returns the old items.

@janukobytsch: I think the problem may be that you open the launcher using `algernon open`. The problem only occurs when you _toggle_ the panel after selecting an entry in the submenu (by using Alt+Space). If you launch the panel using `algernon open` the problem will not occur becaus algernon will be reinitialized.

**Comment by janukobytsch** [comment]
Fixed
